services:
    nginx:
        restart: always
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html/
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/sites/:/etc/nginx/sites-available
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php

    php:
        restart: always
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ./:/var/www/html/
        depends_on:
            - database
        environment:
            PHP_EXTENSION_INTL: 1
            PHP_EXTENSION_GD: 1
            PHP_INI_MEMORY_LIMIT: 1g
            STARTUP_COMMAND_1: composer install
            STARTUP_COMMAND_2: NETTE_DEBUG=1 php bin/console migrations:migrate --no-interaction --allow-no-migration
            STARTUP_COMMAND_3: NETTE_DEBUG=1 php bin/console orm:clear-cache:metadata
            

    database:
        restart: always
        image: mariadb:latest
        volumes:
            - database-volume:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: graphql

    adminer:
        restart: always
        image: adminer:latest
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: database

volumes:
    database-volume:
